### TODO, todo have to store secret inside credential table with proper encryption, and also need id field


@URL = http://localhost:8080
@AUTH_TOKEN = your-token
@secretName = my-secret

### List secrets
GET {{URL}}/api/v1/secrets
Authorization: Bearer {{AUTH_TOKEN}}

### Create secret
POST {{URL}}/api/v1/secrets
Authorization: Bearer {{AUTH_TOKEN}}
Content-Type: application/json

{
  "name": "{{secretName}}",
  "description": "API key for external service",
  "value": "my-secret-value"
}

### Delete secret
DELETE {{URL}}/api/v1/secrets/{{secretName}}
Authorization: Bearer {{AUTH_TOKEN}}