package core

// ContainerSpec is the generic configuration generated by a Runtime adapter
type ContainerSpec struct {
	Image   string
	Cmd     []string
	Env     map[string]string
	Ports   []PortMapping
	GPU     bool
	Storage []StorageSpec
}

type PortMapping struct {
	Port        int
	Protocol    string
	HealthCheck HealthCheckSpec
}

type HealthCheckSpec struct {
	Type           string // "http", "tcp"
	Path           string
	Method         string
	ExpectedStatus int
}

type StorageSpec struct {
	SizeGB    int
	MountPath string
}

// Runtime defines the interface for creating generic container specs
type Runtime interface {
	BuildContainerSpec(modelID string) (*ContainerSpec, error)
	GetWorkloadType() string // e.g., "model_inference", "workload_stateful"
}

// Provider defines the interface for managing cloud/depin deployments
type Provider interface {
	GetMarkets() (interface{}, error)
	CreateDeployment(name string, marketID string, spec *ContainerSpec, replicas int, timeoutMinutes int) (string, error)
	StartDeployment(deploymentID string) error
	StopDeployment(deploymentID string) error
	UpdateTimeout(deploymentID string, timeoutMinutes int) error
	GetStatus(deploymentID string) (string, error)
}
