package core

// ContainerSpec is the generic configuration generated by a Runtime adapter
type ContainerSpec struct {
	Image              string
	Entrypoint         []string
	Cmd                []string
	Env                map[string]string
	Ports              []PortMapping
	GPU                bool
	SystemRequirements SystemRequirements
	Storage            []StorageSpec
	Resources          []ResourceSpec
}

type Endpoint struct {
	Port     int    `json:"port"`
	BaseURL  string `json:"base_url"`
	Protocol string `json:"protocol"` // e.g., "http", "https", "tcp"
}

type StorageSpec struct {
	SizeGB    int
	MountPath string
}

type SystemRequirements struct {
	MinVRAMGB   int
	CUDAVersion string
}

type ResourceSpec struct {
	Type   string
	URL    string
	Target string
	Model  string
}

type PortMapping struct {
	Port        int
	Protocol    string
	HealthCheck HealthCheckSpec
}

type HealthCheckSpec struct {
	Type           string
	Path           string
	Method         string
	ExpectedStatus int
	Headers        map[string]string
	Body           string
}

type ModelInfo struct {
	ID           string   `json:"ID"`
	Name         string   `json:"Name"`
	Author       string   `json:"Author"`
	Architecture string   `json:"Architecture"`
	Downloads    int      `json:"Downloads"`
	PipelineTag  string   `json:"PipelineTag"`
	Tags         []string `json:"Tags"`
}

type Runtime interface {
	BuildContainerSpec(modelID string) (*ContainerSpec, error)
	GetWorkloadType() string // "model_inference", "workload_stateful" etc.
	SearchModels(query string) ([]ModelInfo, error)
	GetModelDetails(modelID string) (interface{}, error)
}

type NodeInfo struct {
	Status    string     `json:"status"`
	Endpoints []Endpoint `json:"endpoints"`
}

type Provider interface {
	GetMarkets() (interface{}, error)
	CreateDeployment(name string, marketID string, spec *ContainerSpec) (string, error)
	StartDeployment(deploymentID string) error
	StopDeployment(deploymentID string) error
	UpdateTimeout(deploymentID string, timeoutMinutes int) error
	GetNodeInfo(providerJobID string) (*NodeInfo, error)
}
